import = [
  "~/.config/alacritty/themes/themes/night_owl.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 7

# decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 16

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

