import = [
  "~/.config/alacritty/themes/themes/night_owl.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 7

decorations = "Buttonless"
opacity = 0.95
blur = false

[font]
normal.family = "FiraCode Nerd Font Mono"
# normal.family = "ComicShannsMono Nerd Font Mono"
size = 19

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"
