set -g default-terminal "screen-256color"

# keymaps
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind v split-window -h

unbind '"'
bind s split-window -v

unbind r
bind r source-file ~/.tmux.conf

# resize pane
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# maximize pane
bind -r m resize-pane -Z
set -g mouse on

# tmp plugin
set -g @plugin 'tmux-plugins/tpm'


# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

# theme
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-status "top" # top | bottom
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-expanded-icon "󰊖 "
set -g @minimal-tmux-indicator-str "#{session_name}"
set -g @minimal-tmux-status-right "#(date +'󰸗 %m月%d日 %a %H:%M')"
set -g @minimal-tmux-status-right-extra ""

# vim copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# unbind neovim conflict
unbind-key -n C-\\
unbind-key -T copy-mode-vi C-\\

# Initialize TMUX plugin manager (keep this line at the very bottoom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
